# Generated by Django 4.2.5 on 2023-09-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_finalplu_revenue1_villageboundary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalPlu',
        ),
    ]
