# Generated by Django 4.2.5 on 2023-09-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customer2'),
        ('home', '0003_delete_finalplu'),
    ]

    operations = [
    ]
